# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
#   - osx # testing on linux should be cover testing on osx for this package
  - windows
julia:
  - 1
  - 1.3
branches:
  only:
    - main
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email: false
# script:
#   - julia --color=yes -e 'using Pkg; Pkg.build()'
#   - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("RiskAdjustedLinearizations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  # - julia -e 'using Pkg; cd(Pkg.dir("RiskAdjustedLinearizations")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
